In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from py_pol.mueller import Mueller, Stokes, np, degrees

In [15]:
M = Mueller().diattenuator_azimuth_ellipticity(p1=0.8, p2=0.2, azimuth=15*degrees, ellipticity=0)
print(M)
S = Stokes().from_components(M.M[:, 0])
print(S.set_depolarization(1).normalize())
M.checks.is_diattenuator()

M = 
[+0.340 +0.260 +0.150 +0.000]   
[+0.260 +0.295 +0.078 +0.000]   
[+0.150 +0.078 +0.205 +0.000]   
[+0.000 +0.000 +0.000 +0.160]   

S depolarized normalized = 
[+1.000]   
[+0.866]   
[+0.500]   
[+0.000]   

1st eigenstate = 
[+1.000]   
[-0.866]   
[-0.500]   
[+0.000]   
 2nd eigenstate = 
[+1.000]   
[+0.866]   
[+0.500]   
[-0.000]   

5.438959822042073e-16 5.438959822042073e-16


array([ True])

In [24]:
p1 = np.random.rand(100) * 0.5 + 0.5
p2 = np.random.rand(100) * 0.5 + 0.5
az = np.random.rand(100) * 180*degrees
el = np.random.rand(100) * 90*degrees - 45*degrees

cond = M.checks.is_diattenuator(give_all=True, verbose=True);
print(cond)

M is a diattenuator:
  Diattenuator
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]
  D > 0
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True

In [24]:
az = 15*degrees
el = 30*degrees
D = np.array([[np.cos(2*az)*np.cos(2*el), np.sin(2*az)*np.cos(2*el), np.sin(2*el)]])
m = D.reshape((3,1)) @ D.reshape((1,3))
print(0.5*m)

[[0.09375    0.05412659 0.1875    ]
 [0.05412659 0.03125    0.10825318]
 [0.1875     0.10825318 0.375     ]]


In [30]:
val, vect = np.linalg.eig(M.M[:,:,0])
for ind in range(4):
    print(val[ind])
    print(vect[:,ind] / vect[0,ind], "\n")

1.1102230246251565e-16
[ 1.        -0.4330127 -0.25      -0.8660254] 

1.0000000000000002
[1.        0.4330127 0.25      0.8660254] 

1.788264138744704e-18
[  1.           3.09366437 -30.79191938   6.18732875] 

-1.925929944387236e-33
[ 1.00000000e+00 -6.73179683e+14  1.99812849e+16 -5.43151027e+15] 



NameError: name 'val' is not defined

In [42]:
from py_pol.jones_matrix import Jones_matrix, Jones_vector

In [39]:
J = Jones_matrix().diattenuator_linear(p1=np.linspace(1, 0.6, 5), p2=np.linspace(0.1, 0.5, 5), azimuth=np.linspace(0, 180*degrees, 5))
print(J)
print(J.M.shape)

J2 = J.M
J2[0,1,2] = 1
J2 = np.moveaxis(J2, -1, 0)
print(J2.shape)
print(J2[2,:,:])

J = 
[+1.000 +0.000]   [+0.550 +0.350]   [+0.300 +0.000]   [+0.550 -0.150]   [+0.600 -0.000]   
[+0.000 +0.100]   [+0.350 +0.550]   [+0.000 +0.800]   [-0.150 +0.550]   [-0.000 +0.500]   

(2, 2, 5)
(5, 2, 2)
[[3.000000e-01+0.j 1.000000e+00+0.j]
 [3.061617e-17+0.j 8.000000e-01+0.j]]


In [51]:
az = 30*degrees
el = 30*degrees
J = Jones_matrix().diattenuator_azimuth_ellipticity(p1=1, p2=0, azimuth=az, ellipticity=el)
E1, E2 = J.parameters.eigenstates(verbose=True);
E1.parameters.azimuth_ellipticity(verbose=True)
E2.parameters.azimuth_ellipticity(verbose=True)

E = Jones_vector().general_azimuth_ellipticity(azimuth=az, ellipticity=el)
print(E.remove_global_phase())

The eigenvectors of J are:
  e1x
[-0.61237244-0.j]
  e1y
[0.35355339+0.70710678j]
  e2x
[-0.79056942+0.j]
  e2y
[-0.27386128-0.54772256j]

The azimuth and ellipticity angles of J e1 are (deg.):
  Azimuth (deg.)
120.00000000000001
  Ellipticity angle (deg.)
-29.99999999999999

The azimuth and ellipticity angles of J e2 are (deg.):
  Azimuth (deg.)
30.00000000000002
  Ellipticity angle (deg.)
29.99999999999998

E = 
[+0.791 + +0.000j]   
[+0.274 + +0.548j]   



In [54]:
S1 = Stokes().from_Jones(E1)
S1.parameters.azimuth_ellipticity(verbose=True)

S2 = Stokes().from_Jones(E2)
S2.parameters.azimuth_ellipticity(verbose=True)

The azimuth of S is (deg):
120.00000000000001
The mean value is 120.00000000000001 +- 0.0

The ellipticity angle of S is (deg):
-29.99999999999999

The azimuth of S is (deg):
30.000000000000004
The mean value is 30.000000000000004 +- 0.0

The ellipticity angle of S is (deg):
29.99999999999999



(0.5235987755982989, 0.5235987755982987)