# Global phase in Mueller

In [1]:
%load_ext autoreload
%autoreload 2
from py_pol.mueller import np, degrees, Mueller, Stokes, Jones_matrix, Jones_vector

In [2]:
# Auxiliar functions
def random_Jones_vector(N):
    az = np.random.rand(N) * 180*degrees
    el = np.random.rand(N) * 90*degrees - 45*degrees
    phase = np.random.rand(N) * 360*degrees
    return Jones_vector().general_azimuth_ellipticity(azimuth=az, ellipticity=el, global_phase=phase)

def random_Jones_diattenuator(N):
    p1 = np.random.rand(N) * 0.5 + 0.5
    p2 = np.random.rand(N) * 0.5
    az = np.random.rand(N) * 180*degrees
    el = np.random.rand(N) * 90*degrees - 45*degrees
    return Jones_matrix().diattenuator_azimuth_ellipticity(p1=p1, p2=p2, azimuth=az, ellipticity=el)

def random_Jones_retarder(N):
    R = np.random.rand(N) * 180*degrees
    az = np.random.rand(N) * 180*degrees
    el = np.random.rand(N) * 90*degrees - 45*degrees
    phase = np.random.rand(N) * 360*degrees
    return Jones_matrix().retarder_azimuth_ellipticity(R=R, azimuth=az, ellipticity=el, global_phase=phase)

def random_Jones_matrix(N):
    Jp = random_Jones_diattenuator(N)
    Jr = random_Jones_retarder(N)
    return Jp * Jr

In [4]:
# Ej 1: Pure Jones
N = 10
E1 = random_Jones_vector(N)
E1.remove_global_phase()
J1 = random_Jones_matrix(N)
J1.remove_global_phase()
J2 = random_Jones_matrix(N)
Ef = J2 * J1 * E1
phase_Jones = Ef.parameters.global_phase()

S1 = Stokes().from_Jones(E1)
M1 = Mueller().from_Jones(J1)
M2 = Mueller().from_Jones(J2)
Sf = M2 * M1 * S1
phase_Mueller = Sf.parameters.global_phase()

print(E1.parameters.global_phase() - S1.parameters.global_phase())
print(J1.parameters.global_phase() - M1.parameters.global_phase())
print(J2.parameters.global_phase() - M2.parameters.global_phase())

print(Sf.parameters.global_phase() - Ef.parameters.global_phase())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.00000000e+00  0.00000000e+00  8.88178420e-16  4.44089210e-16
  0.00000000e+00 -8.88178420e-16  0.00000000e+00 -7.77156117e-16
  8.88178420e-16  0.00000000e+00]


In [15]:
E2 = Jones_vector().from_Stokes(S1)
J1b = Jones_matrix().from_Mueller(M1)

print(E2.parameters.global_phase() - E1.parameters.global_phase())
print(J1b.parameters.global_phase() - J1.parameters.global_phase())

[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.22044605e-16
  0.00000000e+00  0.00000000e+00]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.11022302e-16 0.00000000e+00
 0.00000000e+00 0.00000000e+00]
