In [2]:
from py_pol import degrees, np
from py_pol.mueller import Mueller

In [10]:
M = Mueller().diattenuator_azimuth_ellipticity(azimuth=50*degrees, ellipticity=30*degrees, p1=0.8, p2=0.2)
print(M)

M = 
[+0.340 -0.026 +0.148 +0.260]   
[-0.026 +0.161 -0.008 -0.014]   
[+0.148 -0.008 +0.204 +0.077]   
[+0.260 -0.014 +0.077 +0.295]   



In [11]:
cov = M.covariance_matrix(keep=True)
print(cov)

Covariant of M = 
[+0.112 + +0.000j +0.035 + +0.062j +0.035 + -0.062j +0.125 + +0.000j]   
[+0.035 + -0.062j +0.045 + +0.000j -0.023 + -0.038j +0.039 + -0.068j]   
[+0.035 + +0.062j -0.023 + +0.038j +0.045 + +0.000j +0.039 + +0.068j]   
[+0.125 + +0.000j +0.039 + +0.068j +0.039 + -0.068j +0.138 + +0.000j]   



In [12]:
val, vect = cov.parameters.eig(values_as_matrix=True,
                                               vectors_as_matrix=True,
                                               shape=False)
print(val)
print(vect)

[[ 3.40000000e-01+2.76618222e-18j]
 [-3.10016538e-17+2.37911729e-17j]
 [-6.36405741e-18-1.60948793e-17j]
 [ 1.71749368e-17-6.18226114e-18j]]
[[[ 0.57475216-6.29967255e-17j]
  [-0.53203226+5.85487426e-02j]
  [ 0.07654304-1.90825263e-01j]
  [ 0.01573614+1.60311315e-01j]]

 [[ 0.17913822-3.15063019e-01j]
  [ 0.69904529+0.00000000e+00j]
  [ 0.81540336+0.00000000e+00j]
  [-0.56296211-2.54313883e-02j]]

 [[ 0.17913822+3.15063019e-01j]
  [ 0.35652426-8.74929264e-02j]
  [ 0.24985813-4.58081549e-01j]
  [ 0.66008084+0.00000000e+00j]]

 [[ 0.63792596+0.00000000e+00j]
  [ 0.2261385 -1.97347974e-01j]
  [-0.1418625 +2.12481687e-02j]
  [-0.05401026+4.66750188e-01j]]]


In [13]:
M.checks.is_physical(tol=0, give_all=True, verbose=True)

M is physically realizable:
  Physical
False
  Real elements
[ True]
  M00 >= 0
[ True]
  M00 <= 1
[ True]
  abs(Mij) <= M00
[ True]
  D <= 1
[ True]
  P <= 1
[ True]
  Tmax <= 1
[ True]
  Recip Tmax <= 1
[ True]
  Tr(M*M^T) <= 4*M00^2
[False]
  m cond (D)
[ True]
  m cond (P)
[ True]
  Real eigenvalues
[False]
  Eigenvalues >= 0
[False]
  Eigenvalues <= 1
[ True]



(False,
 [array([ True]),
  array([ True]),
  array([ True]),
  array([ True]),
  array([ True]),
  array([ True]),
  array([ True]),
  array([ True]),
  array([False]),
  array([ True]),
  array([ True]),
  array([False]),
  array([False]),
  array([ True])])

In [14]:
Mrep = M.analysis.filter_physical_conditions(tol=0)

TypeError: ufunc 'arctan2' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [18]:
a = np.random.rand(5) > 0.5
print(a)

[ True False False False False]


In [21]:
# print(not a)
print(np.logical_not(a))

[False  True  True  True  True]


In [1]:
from py_pol.jones_vector import Jones_vector, np

d:\codigo\py_pol\py_pol\jones_vector.py:215: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if other.type is 'Jones_vector':
d:\codigo\py_pol\py_pol\jones_vector.py:235: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if other.type is 'Jones_vector':
d:\codigo\py_pol\py_pol\jones_vector.py:867: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if global_phase is not 0:
d:\codigo\py_pol\py_pol\jones_vector.py:1173: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if global_phase is not 0:
d:\codigo\py_pol\py_pol\utils.py:175: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if new_obj._type is 'Jones_vector':
d:\codigo\py_pol\py_pol\utils.py:181: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif new_obj._type is 'Jones_matrix':


In [2]:
E = Jones_vector().linear_light(np.ones((3,4,5)))

In [3]:
E.parameters.ellipse_axes()

azimuth (60,)
(60,) (60,) (60,) (60,)


(array([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]),
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]))

In [5]:
False == False

True